GCP:
  enabled: false
image:
  tag: v1.0.77-0-ga003eadf8f7d9cdb
analysis:
  config:
    repository:
      persist: true
gateway:
  tls: false
  minReplicaCount: 1
  maxReplicaCount: 10
api:
  minReplicaCount: 1
  maxReplicaCount: 10
otlp:
  endpoint: http://tempo.monitoring:4318
environment:
  domain: eks-gitops.causely.app
