controller:
  type: deployment
agent:
  extraPorts:
    - name: "grpc"
      port: 4317
      targetPort: 4317
    - name: "http"
      port: 4318
      targetPort: 4318
    - name: "zipkin"
      port: 9411
      targetPort: 9411
  configMap:
    content: |
      otelcol.exporter.otlp "causely" {
        client {
          endpoint = "mediator.causely:4317"
          tls {
            insecure = true
          }
        }
      }

      otelcol.exporter.zipkin "lightstep" {
        client {
          endpoint = "lightstepint.internal.com:443"
        }
      }

      prometheus.remote_write "default" {
        endpoint {
          url = "http://kube-prometheus-stack-prometheus.monitoring:9090/api/v1/write"
        }
      }
      
      otelcol.exporter.prometheus "default" {
        forward_to = [prometheus.remote_write.default.receiver]
      }
      
      otelcol.processor.batch "default" {
        output {
          metrics = [otelcol.exporter.prometheus.default.input]
          traces  = [otelcol.exporter.zipkin.lightstep.input, otelcol.exporter.otlp.causely.input]
        }
      }
      
      otelcol.processor.k8sattributes "default" {
        extract {
          label {
            from = "pod"
          }
      
          metadata = [
            "k8s.namespace.name",
            "k8s.pod.name",
            "k8s.pod.uid",
            "k8s.deployment.name",
            "k8s.node.name",
            "k8s.pod.start_time",
          ]
        }
      
        output {
          traces = [otelcol.processor.batch.default.input]
        }
      }
      
      otelcol.receiver.otlp "otlp" {
        grpc {
          endpoint = "0.0.0.0:4317"
        }
        http {
          endpoint = "0.0.0.0:4318"
        }
      
        output {
          metrics = [otelcol.processor.batch.default.input]
          traces  = [otelcol.processor.k8sattributes.default.input]
        }
      }

      otelcol.receiver.zipkin "zipkin" {
        protocols {
          zipkin {
            endpoint = "0.0.0.0:9411"
          }
        }

        output {
            metrics = [otelcol.processor.batch.default.input]
            traces  = [otelcol.processor.k8sattributes.default.input]
        }
      }
