image:
  tag: v1.0.77-0-ga003eadf8f7d9cdb

scrapers:
  istio:
    enabled: true
  prometheus:
    enabled: true
    exporters:
      chaosmania:
        entities:
          - entity:
              workload: {}

            discovery:
              - kubernetes_pod:
                  namespace: "namespace"
                  pod_name: "pod"

            metrics:
              - attribute: TransactionCount
                query: "sum by (namespace, service, pod) (rate(chaosmania_processed_transactions_duration_count[1m]))"
              - attribute: TransactionDuration
                query: "sum by (namespace, service, pod) (rate(chaosmania_processed_transactions_duration_sum[1m]) / (rate(chaosmania_processed_transactions_duration_count[1m]) > 0 or (rate(chaosmania_processed_transactions_duration_count[1m]) + 1)))"
              - attribute: DBQueryDuration
                query: "sum by (namespace, service, pod) (rate(postgres_queries_sum[1m]) / (rate(postgres_queries_count[1m]) > 0 or (rate(postgres_queries_count[1m]) + 1)))"